linters-settings:
  lll:
    line-length: 190
  funlen:
    lines: 70
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 40
  godox:
    keywords:
      - NOTE
      - HACK
  ireturn:
    allow:
      - error
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

run:
  tests: true

linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - depguard
    - varnamelen

issues:
  exclude:
    - "^(G102|G401|G501):"
  exclude-rules:
    - linters: [goerr113]
      text: "do not define dynamic errors, use wrapped static errors instead" # This rule to avoid opinionated check fmt.Errorf("text")
    - path: '(.+)_test\.go'
      linters:
        - maintidx
        - funlen
        - dupl
